# Generated by Django 3.0.2 on 2020-03-06 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Talk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('Vue', 'Vue'), ('React', 'React'), ('Test', 'Test'), ('A11y', 'A11y'), ('Serverless', 'Serverless'), ('How we work', 'How we work'), ('Webpack', 'Webpack'), ('Svelte', 'Svelte'), ('Design', 'Design'), ('Nuxt', 'Nuxt'), ('WebAssembly', 'WebAssembly'), ('Audio', 'Audio'), ('Data', 'Data'), ('Vue3', 'Vue3'), ('eCommerce', 'eCommerce'), ('Climate', 'Climate'), ('Authentication', 'Authentication'), ('CSS Framework', 'CSS Framework'), ('Vuex', 'Vuex'), ('Architecture', 'Architecture')], max_length=25)),
                ('name', models.CharField(default='a title of the talk', max_length=75)),
                ('speaker', models.CharField(max_length=50)),
                ('summary', models.CharField(default='a summary of the talk', max_length=500)),
                ('image', models.FileField(upload_to='')),
                ('slides', models.URLField()),
            ],
        ),
    ]
