# Generated by Django 3.0.2 on 2020-03-06 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talk',
            name='slides',
            field=models.URLField(blank=True, null=True),
        ),
    ]
