# Generated by Django 3.0.2 on 2022-11-19 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200306_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talk',
            name='theme',
            field=models.CharField(choices=[('Vue', 'Vue'), ('Test', 'Test'), ('A11y', 'A11y'), ('Serverless', 'Serverless'), ('How we work', 'How we work'), ('Webpack', 'Webpack'), ('Svelte', 'Svelte'), ('Design', 'Design'), ('Nuxt', 'Nuxt'), ('WebAssembly', 'WebAssembly'), ('Audio', 'Audio'), ('Vue3', 'Vue3'), ('Climate', 'Climate'), ('Vuex', 'Vuex'), ('Architecture', 'Architecture'), ('GraphQL', 'GraphQL')], max_length=25),
        ),
    ]
